version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: foodie-finder-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: foodie-finder
    volumes:
      - mongodb_data:/data/db
    networks:
      - foodie-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: foodie-finder-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/foodie-finder
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - foodie-network

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: foodie-finder-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - foodie-network

volumes:
  mongodb_data:

networks:
  foodie-network:
    driver: bridge